CREATE TABLE spending_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   limit_sum DOUBLE PRECISION NOT NULL,
   limit_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
   limit_currency_shortname VARCHAR(255) NOT NULL,
   limit_category VARCHAR(255) NOT NULL,
   CONSTRAINT pk_spending_limits PRIMARY KEY (id)
);

CREATE TABLE transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   account_to INTEGER NOT NULL,
   account_from INTEGER NOT NULL,
   currency_shortname VARCHAR(255) NOT NULL,
   sum DOUBLE PRECISION NOT NULL,
   category VARCHAR(255) NOT NULL,
   limit_exceeded BOOLEAN NOT NULL,
   datetime TIMESTAMP WITH TIME ZONE NOT NULL,
   CONSTRAINT pk_transactions PRIMARY KEY (id)
);