CREATE TABLE exchange_rates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   base_currency VARCHAR(255) NOT NULL,
   target_currency VARCHAR(255) NOT NULL,
   rate DOUBLE PRECISION NOT NULL,
   date date,
   CONSTRAINT pk_exchange_rates PRIMARY KEY (id)
);